### ISSUE TITLE
Invalid edition [free] for addon rias/statamic-data-import

### ISSUE THREAD

**Issue by noahlocke** [riasvdv/statamic-data-import#11]
Statamic Version: 3.2.31

Hello, I attempted to install this package, but upon installation an error is thrown when attempting to access the Addon via the Statamic Control Panel:

Invalid edition [free] for addon rias/statamic-data-import
<img width="1203" alt="Screen Shot 2022-01-24 at 9 48 47 PM" src="https://user-images.githubusercontent.com/6596677/150907672-4a4bc838-3380-434b-b4a1-c9f73ad55701.png">

**Comment by HazemMohamed252** [comment]
Try to set it via : composer require rias/statamic-data-import
