### ISSUE TITLE
Problem Importing Taggable Fields

### ISSUE THREAD

**Issue by bahamagician** [riasvdv/statamic-data-import#13]
I'm having problems importing taggable fields.

This is my CSV:

![image](https://user-images.githubusercontent.com/13170078/158684283-888ee654-6049-4820-92bd-b90e5d60f4e1.png)

The phone field in statamic is a taggable field
If I import the above CSV, the Steve Irwin entry imports just fine

![image](https://user-images.githubusercontent.com/13170078/158684360-7bbf1b6c-6a35-40c3-98b0-6545cf6ac159.png)

But the Bob Ross field is all kinds of broken

![image](https://user-images.githubusercontent.com/13170078/158684407-eb89b11d-60a6-45a5-be23-965a0b5ee23c.png)

This is the actual md file for Bob Ross....

![image](https://user-images.githubusercontent.com/13170078/158684449-7ba5cfc5-1f00-444c-8a02-38bab6faef47.png)

And this is the Steve Irwin MD file....

![image](https://user-images.githubusercontent.com/13170078/158684483-c4cfe275-d973-417b-afe9-bc7617be3c4a.png)

Is there some sort of additional formatting I can add to the csv to avoid the phone fields with single entries from breaking?

**Comment by riasvdv** [comment]
Does the Bob Ross entry work when you add another number to it? I think the taggable field might expect an array even when it's one value

**Comment by bahamagician** [comment]
> Does the Bob Ross entry work when you add another number to it? I think the taggable field might expect an array even when it's one value

Yea, it works if I add another number to it.  Is there a way to indicate an array of one item within the CSV or is that something that has to be done in the import function?
