### ISSUE TITLE
Filenames should be Statamic id when slugs are not required

### ISSUE THREAD

**Issue by wesort** [riasvdv/statamic-data-import#14]
When a slug isn’t required on a collection, the filename created for each entry should be the Statamic `id`. Currently, the filename is a slugified version of the `title`.

Ideally this would be detected from the collection’s settings. I believe this is a fairly recent option available in Statamic.

Current workaround:
– do the import
– manually rename each new entry’s filename with its `id`

Thanks. Fantastic tool otherwise!

**Comment by riasvdv** [comment]
Seems like it shouldn't be too hard to add. Don't have a lot of time currently to work on issues, so if you're willing to try out a PR it would be very welcome!

**Comment by wesort** [comment]
I wish I could write that PR but I wouldn’t know where to start. 

Would you considered sponsored development on this?
