### ISSUE TITLE
Conflict with versions of spatie/simple-excel

### ISSUE THREAD

**Issue by mscruse** [riasvdv/statamic-data-import#20]
I've encountered an issue where this package is using an old version (1.9) of Spatie's Simple Excel package.

Another part of my site and app is using the latest 3.x version.

Because of this, I am unable to install the Statamic Data Import add-on.

Is it possible to have this add-on updated to support Spatie's 3.x version?

**Comment by mnlmaier** [comment]
+1 Running into this issue aswell

**Comment by riasvdv** [comment]
Should be resolved in 1.3.0!
