### ISSUE TITLE
ErrorException - Undefined array key

### ISSUE THREAD

**Issue by reaboivictor** [riasvdv/statamic-data-import#22]
Hi, maybe someone got this error as well:

![image](https://user-images.githubusercontent.com/69897526/231706816-0ec0cbd3-3138-4673-b00e-6995d573cbac.png)

It fires in `\vendor\rias\statamic-data-import\src\Jobs\ImportJob.php:81`

![image](https://user-images.githubusercontent.com/69897526/231706909-e077791e-0bea-49d7-afd8-eef4eca3c65a.png)

I think it might be because the column's title has a space at the end:

![image](https://user-images.githubusercontent.com/69897526/231705269-0c6cf06c-a3e4-4ae8-b3ff-8b12374ff71a.png)

I could open a PR if someone can assist me

Setup:
PHP - v8.0.13
laravel/framework - v8.83.25
statamic/cms - v3.3.48
rias/statamic-data-import - v1.2.2

**Comment by riasvdv** [comment]
Does it work when you remove the space? It might be easier to just fix your excel/csv file
