### ISSUE TITLE
Error when trying to import

### ISSUE THREAD

**Issue by kupe517** [riasvdv/statamic-data-import#3]
When I am attempting to import a CSV the application throws an error:

![image](https://user-images.githubusercontent.com/5298751/100272986-e69d9000-2f10-11eb-976a-71da853aaf01.png)

PHP Version: 7.3.13-1+ubuntu18.04.1+deb.sury.org+1
Statamic Version: 3.0.30
Statamic Data Import Version: 1.1.0

**Comment by riasvdv** [comment]
This addon only works on php 7.4, as the underlying package that handles the CSVs requires php 7.4
