### ISSUE TITLE
EntrySaved event not triggered

### ISSUE THREAD

**Issue by felixstoessel** [riasvdv/statamic-data-import#8]
Hello,

my initial issue was posted on the statamic/cms repo: https://github.com/statamic/cms/issues/3189

When importing via the addon, the newly created entries do not trigger the EntrySaved event. The famous Jason from Statamic suggested to see if the addon implementation is flawed. If not, we could simply reopen my created issue on the other repo.

**Comment by riasvdv** [comment]
Replied on the issue at Statamic, don't think it's an issue with this addon
